version: "3.8"

services:
  api:
    build: ./simple_api
    container_name: student_api_container
    ports:
      - "5000:5000"
    networks:
      - student_network
    environment:
      - admin=toto
      - pass=python

  website:
    image: php:apache
    container_name: student_website_container
    ports:
      - "8080:80"
    volumes:
      - ./website:/var/www/html
    depends_on:
      - api
    networks:
      - student_network

networks:
  student_network:
    driver: bridge
